### ISSUE TITLE
Instructor - Add Material to a Course Page

### ISSUE THREAD

**Issue by EricHorton** [EricHorton/csc517-program1#13]
Allow Instructors to add notifications to the course page. These should be visible to students.

**Comment by saiteja09** [comment]
Added functionality

**Comment by EricHorton** [comment]
Students can't seem to view materials on the course page. Can you double check?

**Comment by saiteja09** [comment]
Implemented in 1fceb7cb0792924e0c8b3efb2b4cf487bbf77083
